# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20000)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('apic', models.FileField(blank=True, null=True, upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('lang', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=8)),
                ('Category', models.CharField(blank=True, choices=[('Academics', 'Academics'), ('Network Marketing', 'Network Marketing'), ('Self Help', 'Self Help'), ('Biography', 'Biography'), ('Ebook', 'Ebook')], default='Self Help', max_length=30, null=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='pic')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=20000)),
                ('buy', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='bookauthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('about', models.TextField(max_length=20000)),
                ('pic', models.FileField(blank=True, null=True, upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Sachin', max_length=80)),
                ('qty', models.IntegerField(blank=True, default='1')),
                ('price', models.IntegerField(blank=True, default='1')),
                ('stock', models.IntegerField(blank=True, default='1')),
                ('fkbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newbooks.book')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, default='Sachin', max_length=80, null=True)),
                ('datecreate', models.DateTimeField(auto_now=True, null=True)),
                ('bg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newbooks.blog')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookisbn', models.IntegerField()),
                ('name', models.CharField(blank=True, default='Sachin', max_length=80)),
                ('qty', models.IntegerField(blank=True, default='1')),
                ('price', models.IntegerField(blank=True, default='1')),
                ('stock', models.IntegerField(blank=True, default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=300)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(default='Delhi', max_length=25)),
                ('mob', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('fkbook', 'name')]),
        ),
    ]
