# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0002_auto_20170711_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='datecreate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
