# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0003_cart_datecreate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('fkbook', 'name', 'datecreate')]),
        ),
    ]
