# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0004_auto_20170714_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='datecreate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
