# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0007_auto_20170714_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='datecreate',
            new_name='Purchasedate',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([]),
        ),
    ]
