# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0012_auto_20170720_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldorderadd',
            name='name',
        ),
        migrations.DeleteModel(
            name='oldorderadd',
        ),
    ]
