# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0014_oldorderadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldorderadd',
            old_name='datecreate',
            new_name='date',
        ),
    ]
