# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0016_auto_20170721_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oldorderadd',
            unique_together=set([('address', 'mob')]),
        ),
    ]
