# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-23 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0017_auto_20170721_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oldorderadd',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='apic',
        ),
    ]
