# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0018_auto_20170723_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, choices=[('static/bill.jpg', 'sfdgs'), ('static/bill.jpg', 'sfdgs')], null=True, upload_to='pic'),
        ),
    ]
