# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-23 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0020_auto_20170723_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/pic/photo.jpg', null=True, upload_to='pic'),
        ),
    ]
