# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0023_auto_20170723_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='pic'),
        ),
    ]
