# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0024_auto_20170723_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='buy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
