# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0029_likesonpost_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likesonpost',
            unique_together=set([('bg', 'name')]),
        ),
    ]
