# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0030_auto_20170801_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
