# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0031_blog_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like',
        ),
    ]
