# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0034_auto_20170809_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15)),
                ('comm', models.TextField(blank=True, max_length=20000)),
                ('rate', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')])),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
