# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0035_returnbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Returndate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
