# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0036_cart_returndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbook',
            name='orderno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newbooks.cart'),
        ),
    ]
