# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0037_returnbook_orderno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnbook',
            name='orderno',
        ),
    ]
