# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0038_remove_returnbook_orderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbook',
            name='orderno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
