# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0040_auto_20170810_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='rate',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3)], default='1'),
        ),
    ]
