# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0043_auto_20170813_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='ContactNo',
            field=models.IntegerField(),
        ),
    ]
