# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0047_auto_20170813_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default='1'),
        ),
    ]
