# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0048_auto_20170813_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnbook',
            old_name='orderno',
            new_name='order_no',
        ),
        migrations.AlterUniqueTogether(
            name='returnbook',
            unique_together=set([('order_no', 'isbn')]),
        ),
    ]
