# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0049_auto_20170814_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnbook',
            old_name='comm',
            new_name='comment',
        ),
    ]
