# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0050_auto_20170814_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='buy',
            new_name='review',
        ),
    ]
