# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0052_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verify',
            name='otp',
        ),
    ]
