# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0054_resetpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpass',
            name='user',
            field=models.CharField(max_length=60),
        ),
    ]
