# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0055_auto_20171206_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpass',
            old_name='date_created',
            new_name='purchase_date',
        ),
    ]
