# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0056_auto_20171206_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpass',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
