# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0057_auto_20171206_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpass',
            name='id',
        ),
        migrations.AddField(
            model_name='resetpass',
            name='auto_increment_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
