# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0059_auto_20171206_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpass',
            old_name='auto_increment',
            new_name='id',
        ),
    ]
