# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0061_auto_20171206_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpass',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='serialid',
            field=models.IntegerField(null=True),
        ),
    ]
