# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0065_auto_20171206_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpass',
            name='num',
        ),
    ]
