# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0066_remove_resetpass_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpass',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
