# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0067_resetpass_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpass',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='resetpass',
            name='purchase_date',
        ),
    ]
