# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0068_auto_20171206_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpass',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='resetpass',
            name='serialid',
            field=models.IntegerField(null=True),
        ),
    ]
