# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0070_auto_20171207_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
