# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0071_verify_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
