# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0072_shipping_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='user',
        ),
    ]
