# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0075_auto_20171212_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selectadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('select', models.IntegerField()),
            ],
        ),
    ]
