# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0077_auto_20171212_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectadd',
            name='payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
