# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0078_selectadd_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar',
            field=models.BigIntegerField(default='123456789'),
        ),
    ]
