# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0079_profile_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.IntegerField(default='0'),
        ),
    ]
