# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-07 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbooks', '0081_auto_20180407_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsorid',
            field=models.IntegerField(blank=True),
        ),
    ]
